### PR TITLE
Add table for logging Video Widget memory usage

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi @stulees What do you think of this table structure for logging memory usage? Do you think any of these fields should be nullable?

**Comment by stulees** [comment]
@donnapep I'm not sure if values for those will always be accessible, do you know?

**Comment by donnapep** [comment]
@stulees Not sure. @rodrigopavezi What's your experience been?

**Comment by rodrigopavezi** [comment]
@donnapep @stulees they are always accessible. I was wondering what would be the best approach when we change the test presentation. We should not mix data from a test presentation with another. Do you know what I mean? Should we add a column for that or add a table for each time we change the presentation? cheers

**Comment by donnapep** [comment]
@rodrigopavezi We could see if we could pass the Display ID so that we could filter by Display ID. Only problem is I'm not sure if we can get the Display ID in the Presentation HTML.

**Comment by donnapep** [comment]
Actually, @rodrigopavezi, the script will pass the Display ID in the URL, correct? If so, I think we can get it that way.

**Comment by rodrigopavezi** [comment]
@donnapep good point! yes the display id is passed on the URL such as http://rvashow.appspot.com/Viewer.html?type=display&player=true&id=FG5YVBJDTXB2

I guess we will just to have to remember to not run different presentations on the same display id. 
cheers

**Comment by donnapep** [comment]
@rodrigopavezi @stulees OK, I've added `display_id`. Are we good with the table structure? Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good. :+1:  cheers

**Pull request merged**
