### PR TITLE
Adding additional fields to Widget_Event table

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @tejohnso Please review, thanks

**Comment by donnapep** [comment]
:+1:

**Comment by donnapep** [comment]
@stulees Actually, should we also have a separate field for the URL instead of stuffing it into event_details?

**Comment by stulees** [comment]
@donnapep As in `file_url` then? In thinking beyond just Video widget, what do you think we should preserve `event_details` for? I'm also wondering if we're introducing too many Video specific fields, but I guess it won't matter since we ensure they're nullable.

**Comment by donnapep** [comment]
@stulees Yes, a `file_url` field. And I think we should probably leave this PR open for now since it's unclear as to whether or not we'll be able to determine the file size.

Alan and I talked about having too many video-specific fields, but he didn't seem concerned. I'm thinking that it might be better to drop the `widget` column and give each Widget its own table with their own fields. Thoughts?

**Comment by donnapep** [comment]
@stulees Actually, I think we need to use separate tables per Widget in order to follow proper database design. Otherwise, it will grow to be a real mess and get really confusing.

**Comment by stulees** [comment]
@donnapep I agree, each Widget could have its own table within the Widget_Events data set. We'll have to modify how we name our tables as they'll have to include the widget name within the prefix. So it should go: `video_eventsyyyymmdd`, `spreadsheet_eventsyyyymmdd`, etc. 

If agreed, I'm going to close this PR. I'll manually create todays new table for Video, and issue a new PR to this repo for the changes. I don't think it should remain open because of uncertainty of retrieving file size. The field is nullable and also the eventual PR will need merging so that the tables get automatically created for each day.

**Comment by donnapep** [comment]
@stulees Yes, let's close this one. Thx.

**Pull request closed without merging**
