### PR TITLE
Use correct table name for apps

### PR DESCRIPTION
**Pull request by alex-deaconu**
We have been creating the wrong table for years. Updating to create the correct table. Validated that the schema is the same.

Not really sure how to test this. @tejohnso any ideas?

@ezequielc @tejohnso please review. Thanks!

### CODE REVIEW

**Comment by tejohnso** [comment]
@alex-deaconu How is Apps_Events.apps_events being created if not here? And if it is being created elsewhere, do we need it here? And finally, how sure are we that Apps_Events.events is not being used?

**Comment by alex-deaconu** [comment]
@tejohnso the `Apps_events.apps_events` table is the main logging table for Apps. I believe it is being created ad hoc by the store-server (https://github.com/Rise-Vision/store-server/blob/master/src/main/java/com/risevision/store/BQUtils.java#L51-L53) via the `streamInsert`. The library automatically creates the table if it's missing.

I've investigated issues in the past where the table was missing when called via the Client Side functions (either in Viewer or Apps) early in the morning before the store-server created it.

This task should be creating the table a day in advance preventing the issue.

Re: `Apps_Events.events` I'm pretty certain it's not being used. I haven't found any references to that table, and every table instance I've checked is empty.

Thanks.

**Comment by alex-deaconu** [comment]
@tejohnso @ezequielc to confirm, an alternative is to just remove the `Apps_Events.events` table creation and skip adding `Apps_Events.apps_events` creation, relying on existing mechanisms. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu @tejohnso I am good with either approach. Thanks

**Comment by tejohnso** [comment]
@alex-deaconu I don't think we should have the same table created using two different mechanisms. I prefer your alternative.

**Comment by alex-deaconu** [comment]
@tejohnso @ezequielc as per discussions, I've just removed the `Apps_Events.events` table creation altogether. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks good to me 👍

**Review by tejohnso — APPROVED** [review]
:+1:

**Pull request merged**
